site: plan2k22
title: plan2k22
greetings: Namasthe 👋
description: >-
  just a minimalist, personal blog
lang: en-US
timezone:  Asia/Kolkata
repo: https://github.com/mnk17arts/plan2k22 # site repo [optional]
data-theme: dark # default theme "dark" | "light"

author:
  name: mnk17arts
  bio: just a minimalist, personal blog
  userpicture: 
  username: mnk17arts # general username
  github: mnk17arts # github username
  twitter: mnk17arts # twitter username
  email: mnk17arts@email.com # email adress

# Font Settings
googlewebfonts: family=Play:wght@400;700&family=Source+Code+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,300;1,400;1,500;1,600;1,700;1,900

# URL settings
url: "https://mnk17arts.github.io" # Domain Name of host. [username].github.io for github pages
baseurl: "/plan2k22" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
permalink: pretty

# local
# url: "http://localhost:4000" # 
# baseurl: "" # 


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false


